lang: en
title: AstroMeters.eu
tagline: Precision Components for Your Telescope Assembly
email: info@astrometers.eu
description: >-
  AstroMeters specializes in high-quality astronomical components including precision focusers, 
  mount controllers, and environmental sensors. Open-source solutions designed by astronomy 
  enthusiasts for enhanced stargazing and astrophotography experiences.
baseurl: ""
url: "https://astrometers.eu"
author:
  name: AstroMeters
  email: roman.dvorak@astrometers.eu
  twitter: 
  links:
    - https://github.com/AstroMeters
    - https://astrometers.eu
github_username:  AstroMeters
permalink: pretty
theme_color: '#1c305c'
google_analytics: G-NBPYLMPRY4

gh_sponsor: false
hide_footer: true

social:
  facebook: false
  instagram: false
  threads: false
  tiktok: false
  x: false
  youtube: false

markdown: kramdown
theme: bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

collections:
  products: 
    output: true
    layout: product
    image: ''
    hero_image: '/images/docs.jpg'
    show_sidebar: false

paginate: 5
paginate_path: "/blog/page:num"

disqus: false

# SEO Configuration
seo:
  type: Organization
  name: AstroMeters
  links:
    - https://github.com/AstroMeters
    - https://astrometers.eu

# Social media defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AstroMeters Team"
      image: "/images/docs.jpg"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      author: "AstroMeters Team"
  - scope:
      path: ""
      type: "pages"
    values:
      author: "AstroMeters Team"
      image: "/images/docs.jpg"

# Structured data
organization:
  name: AstroMeters
  url: https://astrometers.eu
  logo: https://astrometers.eu/images/logo.png
  sameAs:
    - https://github.com/AstroMeters

# Feed configuration
feed:
  posts_limit: 20
  excerpt_only: false
